### ISSUE TITLE
Air-gapped install is failing

### ISSUE THREAD

**Issue by satadruroy** [cloudfoundry-incubator/kubecf#1153] opened 2020-07-21 19:39 UTC
From @HartS 

After developing a process to deploy kubecf in an environment which would simulate an airgapped deployment, I found that kubecf would not install in this scenario.

Measures taken to ensure that kubecf and kubernetes could not reach the internet:

Set some iptables rules on all kube/CaaSP nodes to prevent internet access from those nodes. Outgoing traffic is blocked by the rules
Apply a CiliumNetworkPolicy in the cf-operator and scf namespaces to restrict internet access from the pods/containers in those namespaces (otherwise those containers are able to bypass the iptables rules)
Mirror all required images from a docker registry running on the master node, and configure the kubecf deployment to use mirrored images in a multitude of places
After ironing out the above details and verifying that internet access was in fact restricted, images could still be pulled from the mirror registry, etc. I began seeing the following while attempting to deploy kubecf v2.2.2:

cf-operator would install successfully
As kubecf would start to come up in the scf namespace, several containers would never come up (many are stuck in state where they are running with not all containers ready). Following the logs of containers which weren't becoming ready, most appeared to be waiting on other pods via the wait-for container. From following these, I could ultimately see that the diego-api pod would be stuck waiting for adapter (`wait-for` pod would show logs stating it was waiting for the adapter.
confusingly, adapter would be running. All containers ready with no indication of error.
This was reproduced on three bare-metal CaaSP clusters provisioned by Chris Olstrom (x8 and x9, which run in the Vancouver, and p89 running in Provo).

After reproducing the same issue on all deployments, I turned the airgapped simulation off and attempted some more kubecf deployments. This time,  on p89, kubecf (v2.2.2 still) was able to deploy without any issues

**Comment by viovanov** [comment] 2020-07-30 16:35
The internetless CI run should be airgapped, i.e. don't install with internet access, then remove it.

**Comment by mook-as** [comment] 2020-08-04 21:19
> diego-api pod would be stuck waiting for adapter 
> confusingly, adapter would be running

I've seen similar behaviour when I mess up the DNS; I believe the `diego-api` → `adapter` wait is the first one to be resolved in a deployment, and that works by doing a DNS lookup (so if DNS is busted it'll be stuck there).

Currently trying to deploy (on minikube):
- Build the bundle
- `docker pull` all the images specified in the operator/kubecf charts' `imagelist.txt` files
- Cut off internet access by turning off that NAT network in libvirt
- Attempt to deploy.

**Comment by mook-as** [comment] 2020-08-04 22:42
I can't reproduce: I can deploy fine with the above steps. I have confirmed that I can't contact `www.google.com` (or by its IP, `172.217.14.196`).

I can't run smoke tests because I can't look up the CF API domain (`….xip.io`).

@HartS Do you have any more information on this? I'm particularly interested in the state of the `bosh-dns` pods in that situation.

@viovanov 
> The internetless CI run should be airgapped, i.e. don't install with internet access, then remove it.

If we want that, we need a different issue.

**Comment by mook-as** [comment] 2020-08-18 23:15
@HartS got me access to a cluster that's reproducing this.  As far as I can tell, something is busted with the DNS there: none of the kubecf pods can contact DNS (as in, the packets get dropped), so waiting for things to finish never happen.  Actually, initially even the non-kubecf pods are having issues with DNS…

I'm going to resolve this as not an issue with kubecf, but an issue somewhere in the set up of the airgapped cluster: intra-cluster communication is not expected to be broken (and we can't support such a setup).

**Closed by mook-as** 2020-08-18 23:15 UTC
Labels: Priority: Critical, Status: Need More Info, Type: Bug, suse-cap
