### ISSUE TITLE
Not all replicas get ready on an HA deployment 

### ISSUE THREAD

**Issue by satadruroy** [cloudfoundry-incubator/kubecf#453] opened 2020-03-06 01:04 UTC
kubecf-bundle-v0.0.0-fe39c84.tgz

Vanilla KubeCF HA deployment on EKS, 3 t2.large nodes (`set ha_availability=true`) 

`auctioneer`, `diego-api` and `routing-api` containers in the 2nd replica fail with locket errors:

```{"timestamp":"2020-03-05T23:57:29.902811486Z","level":"error","source":"routing-api","message":"routing-api.locket-lock.failed-to-acquire-lock","data":{"error":"rpc error: code = AlreadyExists desc = lock-collision","lock":{"key":"routing_api_lock","owner":"routing-api-1","type_code":1},"request-uuid":"b4c2954f-3771-4885-7f10-99d33392d160","session":"12","ttl_in_seconds":15}}```

```kubecf-adapter-0                   4/4     Running   0          39m
kubecf-adapter-1                   4/4     Running   0          37m
kubecf-api-0                       15/15   Running   1          39m
kubecf-api-1                       15/15   Running   1          30m
kubecf-auctioneer-0                4/4     Running   1          39m
kubecf-auctioneer-1                3/4     Running   1          30m
kubecf-bosh-dns-7787b4bb88-gd2qp   1/1     Running   0          40m
kubecf-bosh-dns-7787b4bb88-whtx6   1/1     Running   0          40m
kubecf-cc-worker-0                 4/4     Running   0          39m
kubecf-cc-worker-1                 4/4     Running   0          30m
kubecf-credhub-0                   5/5     Running   0          39m
kubecf-credhub-1                   5/5     Running   0          26m
kubecf-database-0                  2/2     Running   0          40m
kubecf-diego-api-0                 6/6     Running   2          39m
kubecf-diego-api-1                 5/6     Running   2          36m
kubecf-diego-cell-0                7/7     Running   2          39m
kubecf-diego-cell-1                7/7     Running   2          27m
kubecf-diego-cell-2                7/7     Running   2          23m
kubecf-doppler-0                   9/9     Running   0          39m
kubecf-log-api-0                   7/7     Running   0          39m
kubecf-log-api-1                   7/7     Running   0          27m
kubecf-nats-0                      4/4     Running   0          40m
kubecf-nats-1                      4/4     Running   0          37m
kubecf-router-0                    5/5     Running   0          39m
kubecf-router-1                    5/5     Running   0          29m
kubecf-routing-api-0               4/4     Running   0          39m
kubecf-routing-api-1               3/4     Running   0          30m
kubecf-scheduler-0                 10/10   Running   1          39m
kubecf-scheduler-1                 10/10   Running   1          30m
kubecf-singleton-blobstore-0       6/6     Running   0          40m
kubecf-tcp-router-0                5/5     Running   0          39m
kubecf-tcp-router-1                5/5     Running   0          29m
kubecf-uaa-0                       6/6     Running   0          39m
kubecf-uaa-1                       6/6     Running   0          33m```

**Comment by mook-as** [comment] 2020-03-06 01:18
That sounds like we need to fix the active/passive probes; quarks appears to [support it](https://github.com/cloudfoundry-incubator/cf-operator/blob/master/docs/controllers/quarks_statefulset.md#quarksstatefulset-active-passive-controller) but I don't know yet how we can [propagate that](https://github.com/cloudfoundry-incubator/cf-operator/blob/master/docs/from_bosh_to_kube.md#Support-for-activepassive-pod-replicas). We will probably need to see what comes out of [#170883970](https://www.pivotaltracker.com/story/show/170883970).

**Comment by bikramnehra** [comment] 2020-03-17 20:01
I am not able to reproduce the issue both on `minikube` and `EKS`, here are the logs with recent `EKS` deployment:

[pods.log](https://github.com/cloudfoundry-incubator/kubecf/files/4345574/pods.log)
[smokes.log](https://github.com/cloudfoundry-incubator/kubecf/files/4345575/smokes.log)

**Comment by bikramnehra** [comment] 2020-03-17 21:11
Closing for now as its not reproducible.

**Closed by bikramnehra** 2020-03-17 21:11 UTC
Labels: Priority: Medium, Status: Validation, Type: Bug
