### ISSUE TITLE
Eirini apps do not automatically start after kube outage (Failed to create a kube secret)

### ISSUE THREAD

**Issue by troytop** [cloudfoundry-incubator/kubecf#1485] opened 2020-10-14 17:09 UTC
**Describe the bug**

My SUSE CaaSP 4.5 (k8s v1.18.6) cluster rolls worker nodes with `kured` periodically. This causes some (expected) downtime for my KubeCF 2.5.8 cluster components.

Apps run by Eirini do not start up when the cluster comes back online. All apps show up as  "Deployed - Starting App" and are not running. There are no pods present in the eirini namespace, and the apps stay in this state till I issue a restart command via cf/stratos at which point they come up normally.

The statefulset for one of the stopped apps shows the following error:

```
Warning  FailedCreate  2m43s (x157 over 38h)  statefulset-controller  create Pod mongoblog-dev-09879c6424-0 in StatefulSet mongoblog-dev-09879c6424 failed error: admission webhook "0.eirini-ssh.org" denied the request: Failed to create a kube secret for the application SSH key: secrets "5f7b2c83-8e72-40ae-8dde-dcc17bd46f26-66d2427e-c63f-4d40-8651-e40531c225af-0-ssh-key-meta" already exists
```

**To Reproduce**

Deploy KubeCF 2.5.8 with Eirini enabled. Reboot nodes(?) or do a rolling restart using kured.

**Expected behavior**

CF Apps should come back to a running state automatically.

**Comment by viovanov** [comment] 2020-11-05 17:48
Duplicate of #1548

**Closed by viovanov** 2020-11-05 17:48 UTC
Labels: Priority: High, Status: Accepted, Type: Bug
