### ISSUE TITLE
EiriniX crashed after applying a change to values.yaml

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/kubecf#729] opened 2020-04-20 22:34 UTC
**Describe the bug**

Logs from `eirini-loggregator-bridge-eirini-loggregator-bridge`:
```
{"level":"info","ts":1587421772.3172147,"caller":"config/getter.go:53","msg":"Using in-cluster kube config"}
{"level":"info","ts":1587421772.3172426,"caller":"config/checker.go:36","msg":"Checking kube config"}
Received non-pod object in watcher channel
Watcher channel closed
```

**To Reproduce**

1. Deploy with Eirini.
2. Apply a change to `values.yaml`, in my case, I changed the number of nodes on CATS:
From:
```yaml
properties:
  acceptance-tests:
    acceptance-tests:
      acceptance_tests:
        ginkgo:
          nodes: 6
```
To:
```yaml
properties:
  acceptance-tests:
    acceptance-tests:
      acceptance_tests:
        ginkgo:
          nodes: 1
```

After the KubeCF installation gets updated, Eirini crashes.

**Expected behavior**

Eirini should not crash.

**Environment**

Tip of `master`.

**Comment by viovanov** [comment] 2020-04-23 07:19
does this happen with the new native Eirini helm chart @f0rmiga ?

**Comment by mook-as** [comment] 2020-04-23 14:14
FWIW, I've been seeing this in my eirinix helm chart work; it does not happen on the _first_ deployment in a cluster (deleting the kubecf namespaces doesn't fix it).  Probably means eirinix is creating something and then falling over if it already exists.

[`PodWatcher.Handle`](https://github.com/SUSE/eirini-loggregator-bridge/blob/8c8504b7c3a5efaee58b0f4d9b6bd65de828639d/podwatcher/podwatcher.go#L232) isn't checking for `e.Type == watch.ERROR`; adding that and dumping the event says something about `too old resource version`, IIRC.  Currently suspecting [this](https://github.com/SUSE/eirinix/blob/85a6c535b0ad895e28b5537f99045f0a8aeeec11/manager.go#L239) but I'm not very confident about it.

**Comment by mudler** [comment] 2020-04-29 08:08
> FWIW, I've been seeing this in my eirinix helm chart work; it does not happen on the _first_ deployment in a cluster (deleting the kubecf namespaces doesn't fix it). Probably means eirinix is creating something and then falling over if it already exists.
> 
> [`PodWatcher.Handle`](https://github.com/SUSE/eirini-loggregator-bridge/blob/8c8504b7c3a5efaee58b0f4d9b6bd65de828639d/podwatcher/podwatcher.go#L232) isn't checking for `e.Type == watch.ERROR`; adding that and dumping the event says something about `too old resource version`, IIRC. Currently suspecting [this](https://github.com/SUSE/eirinix/blob/85a6c535b0ad895e28b5537f99045f0a8aeeec11/manager.go#L239) but I'm not very confident about it.

I think you are right, probably we need to handle the starting event as described here: https://github.com/kubernetes/client-go/blob/master/tools/watch/until.go#L175

**Comment by mudler** [comment] 2020-04-30 12:09
EiriniX changes: https://github.com/SUSE/eirinix/pull/38 (ready for review), loggregator-bridge: https://github.com/SUSE/eirini-loggregator-bridge/pull/17 (Draft, need to test on a KubeCF deployment)

**Comment by mudler** [comment] 2020-05-04 10:04
Waiting for https://github.com/cloudfoundry-incubator/kubecf/pull/800 to confirm that the issue is fixed by the above changes

**Closed** 2020-05-05 14:47 UTC
Labels: Priority: High, Type: Bug, suse-cap
