### ISSUE TITLE
UAA DB Migration fails with bad SQL error with Maria external DB (works with MySQL/Postgres) 

### ISSUE THREAD

**Issue by satadruroy** [cloudfoundry-incubator/kubecf#636] opened 2020-04-08 19:25 UTC
KubeCF 1.0.1 running on EKS with Kube 1.15 and an external database MariaDB RDS.

The values yaml:

```system_domain: kubecf.sroy.aws.howdoi.website
features:
    embedded_database:
        enabled: false
    external_database:
        emabled: true
        require_ssl: false
        type: mysql
        host: k8scfdb.cryv2qwmdwrh.us-east-2.rds.amazonaws.com
        port: 3306
        databases:
          uaa:
            name: uaa
            password: ******
            username: adminkubecfdb
<rest snipped>
```

During startup, the uaa-uaa container in the UAA pod goes into a CLBO:

```kubecf-adapter-0                   4/4     Running            0          18h
kubecf-api-0                       0/15    Init:30/63         37         18h
kubecf-auctioneer-0                0/4     Init:5/9           37         18h
kubecf-bosh-dns-86784b95f7-6lzzt   1/1     Running            0          18h
kubecf-bosh-dns-86784b95f7-77294   1/1     Running            0          18h
kubecf-cc-worker-0                 0/4     Init:5/9           37         18h
kubecf-credhub-0                   0/6     Init:7/13          37         18h
kubecf-diego-api-0                 6/6     Running            2          18h
kubecf-diego-cell-0                0/7     Init:8/20          37         18h
kubecf-doppler-0                   0/9     Init:7/16          37         18h
kubecf-log-api-0                   0/7     Init:6/13          37         18h
kubecf-nats-0                      4/4     Running            0          18h
kubecf-router-0                    0/5     Init:5/11          37         18h
kubecf-routing-api-0               0/4     Init:5/10          37         18h
kubecf-scheduler-0                 0/10    Init:8/19          37         18h
kubecf-singleton-blobstore-0       0/6     Init:6/11          37         18h
kubecf-tcp-router-0                0/5     Init:5/11          37         18h
kubecf-uaa-0                       6/7     CrashLoopBackOff   12         45m
```

It's almost impossible to `exec` into the `uaa-uaa` container to check the `/var/vcap/sys/log/uaa/uaa.log` as it keeps crashing but looking at the database it appears 3 migrations ran but the last one failed.

```mysql> select * from schema_version;
+----------------+---------+------------------------------+-------------+-----------------------------------------------------------------------------+------------+---------------+---------------------+----------------+---------+
| installed_rank | version | description                  | type        | script                                                                      | checksum   | installed_by  | installed_on        | execution_time | success |
+----------------+---------+------------------------------+-------------+-----------------------------------------------------------------------------+------------+---------------+---------------------+----------------+---------+
|              1 | 1.5.2   | initial db                   | SQL         | V1_5_2__initial_db.sql                                                      | 1411993333 | adminkubecfdb | 2020-04-08 18:38:44 |            140 |       1 |
|              2 | 1.5.3   | InitialDBScript              | JDBC        | org.cloudfoundry.identity.uaa.db.mysql.V1_5_3__InitialDBScript              |       NULL | adminkubecfdb | 2020-04-08 18:38:44 |             26 |       1 |
|              3 | 1.5.4   | NormalizeTableAndColumnNames | SPRING_JDBC | org.cloudfoundry.identity.uaa.db.mysql.V1_5_4__NormalizeTableAndColumnNames |       NULL | adminkubecfdb | 2020-04-08 19:18:25 |             67 |       0 |
+----------------+---------+------------------------------+-------------+-----------------------------------------------------------------------------+------------+---------------+---------------------+----------------+---------+
3 rows in set (0.01 sec)
```

Dropping the uaa db, recreating it does not help - the container fails at the same step. As for the rest, one of the conatainers in the `blobstore` pod is stuck waiting on `uaa` while a similar wait container in `kubecf-api-0` is stuck waiting on the `blobstore`.

The same setup (maria on AWS) worked with SCF on EKS.

**Comment by satadruroy** [comment] 2020-04-10 07:33
It took me a while to get the actual logs. TIL that all the container logs on `/var/vcap/sys` are actually volume mounted via an `emptyDir` (`sys-dir`) so you can access a container's logs from any other container even though the container in question may be in CLBO. 

Anyway...here is the problem: the migration fails due to bad SQL syntax for Maria:

```Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ALTER TABLE authz_a
pprovals CHANGE expiresAt expiresat timestamp  NOT NULL DEFAULT ''2001-01-01 01:01:01.000001']; nested exception is
 java.sql.SQLSyntaxErrorException: (conn=63026) You have an error in your SQL syntax; check the manual that corresp
onds to your MariaDB server version for the right syntax to use near '2001-01-01 01:01:01.000001'' at line 1
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLException
Translator.java:235) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExc
eptionTranslator.java:72) ~[spring-jdbc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443) ~[spring-jdbc-5.2.
3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388) ~[spring-jdbc-5.2.3.RELEASE.ja
r:5.2.3.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:418) ~[spring-jdbc-5.2.3.RELEASE.ja
r:5.2.3.RELEASE]
        at org.cloudfoundry.identity.uaa.db.mysql.V1_5_4__NormalizeTableAndColumnNames.migrate(V1_5_4__NormalizeTab
```

**Comment by satadruroy** [comment] 2020-04-14 04:26
Tried on MySQL 8.0 - doesn't work due to usage of reserved keyword for table name `groups`:

```Migration V1_5_2__initial_db.sql failed
---------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=63186) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups (
Location   : org/cloudfoundry/identity/uaa/db/mysql/V1_5_2__initial_db.sql (/var/vcap/jobs/uaa/file:/var/vcap/data/uaa/tomcat/webapps/ROOT/WEB-INF/lib/cloudfoundry-identity-server-74.14.0.jar!/org/cloudfoundry/identity/uaa/db/mysql/V1_5_2__initial_db.sql)
Line       : 76
Statement  : CREATE TABLE groups (
  id VARCHAR(36) not null primary key,
  displayName VARCHAR(255) not null,
  created TIMESTAMP default current_timestamp not null,
  lastModified TIMESTAMP null,
  version INTEGER default 0 not null,
  constraint unique_uk_2 unique(displayName)
)```

I supposed we never tested SCF with MySQL 8.0.

**Comment by satadruroy** [comment] 2020-04-14 05:25
...and MySQL 5.7 works perfectly fine.

So, at this point, MariaDB doesn't work and I don't understand why https://github.com/cloudfoundry/uaa/blob/c25e9b37e06e6303673fb921b3d43acfae88cfcf/server/src/main/java/org/cloudfoundry/identity/uaa/db/mysql/V1_5_4__NormalizeTableAndColumnNames.java#L52 generates 
```bad SQL grammar [ALTER TABLE authz_a
pprovals CHANGE expiresAt expiresat timestamp  NOT NULL DEFAULT ''2001-01-01 01:01:01.000001']; nested exception is
 java.sql.SQLSyntaxErrorException: (conn=63026) You have an error in your SQL syntax; check the manual that corresp
onds to your MariaDB server version for the right syntax to use near '2001-01-01 01:01:01.000001'' at line 1
```

The exact same code appears to work fine for SCF.

**Comment by satadruroy** [comment] 2020-04-14 20:47
Postgres works too...one thing to note is, apart from seeding the databases we also need to create extension type for each database as in the following:

```
psql -h pgsql-kubecf.postgres.database.azure.com -p 5432 -U dbadmin@pgsql-kubecf -W -d postgres
Password:
psql (12.2, server 10.11)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=> \c cloud_controller
Password for user dbadmin@pgsql-kubecf:
psql (12.2, server 10.11)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
You are now connected to database "cloud_controller" as user "dbadmin@pgsql-kubecf".
cloud_controller=> CREATE EXTENSION citext;
CREATE EXTENSION
cloud_controller=> \c diego;
Password for user dbadmin@pgsql-kubecf:
psql (12.2, server 10.11)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
You are now connected to database "diego" as user "dbadmin@pgsql-kubecf".
diego=> CREATE EXTENSION citext;
CREATE EXTENSION
```
Otherwise, `kubecf-api-0` will go into a CLBO with `ERROR: type "citext" does not exist`

**Comment by satadruroy** [comment] 2020-04-14 20:56
So, here is the summary:

MySQL 5.7/5.8 (but not 8.0) works with KubeCF.
Postgres 10 works with KubeCF.

MariaDB 10.x does NOT work with KubeCF: the uaa DB migration fails with 
```bad SQL grammar [ALTER TABLE authz_approvals CHANGE expiresAt expiresat timestamp  NOT NULL DEFAULT ''2001-01-01 01:01:01.000001']; nested exception is
 java.sql.SQLSyntaxErrorException: (conn=63026) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '2001-01-01 01:01:01.000001'' at line 1
```
The offending line is : https://github.com/cloudfoundry/uaa/blob/c25e9b37e06e6303673fb921b3d43acfae88cfcf/server/src/main/java/org/cloudfoundry/identity/uaa/db/mysql/V1_5_4__NormalizeTableAndColumnNames.java#L52

(though I can't spot any obvious error in that sql fragment that will get generated)

Now, the reason MariaDB worked with SCF is the UAA db was named `uaadb` and therefore, https://github.com/cloudfoundry/uaa/blob/4653a99a88c49d4b1b680b6592ed39f90de68210/server/src/main/java/org/cloudfoundry/identity/uaa/db/mysql/V1_5_4__NormalizeTableAndColumnNames.java#L42 never returned any results and so line 52 above was never executed. 

So, technically this is not a regression for *us* but we should probably file a bug with upstream UAA. No idea why that statement works with MySQL but not with Maria. 

@viovanov @f0rmiga ^^^

**Comment by jandubois** [comment] 2020-04-14 21:18
> (though I can't spot any obvious error in that line but somehow the generated SQL seems to miss a `'`)

The problem is the greedy regular expression:

```
column.sql.replaceAll("2001-01-01 .*", "'2001-01-01 01:01:01.000001'");
```

The `.*` at the end will include the trailing apostrophe, but the one at the beginning will not be matched, so stays in place. A better expression would be

```
column.sql.replaceAll("'2001-01-01 .*'", "'2001-01-01 01:01:01.000001'");
```

**Comment by satadruroy** [comment] 2020-04-16 00:17
MariaDB 10.1.34 works! 

What works:

| DB                  | Versions     |
| ------------- | ------------- |
| MySQL  | 5.7, 5.8  |
| MariaDB  | 10.1.34 |
|Postgres  |  10 |

What does **not** work:

MySQL : 8.0
MariaDB: 10.2.x

**Comment by satadruroy** [comment] 2020-04-16 16:39
Final update:

Relevant uaa log fragment for MariaDB 10.1.34 (works):

```
[2020-04-15 23:04:48.652] uaa - 23 [main] .... 
 INFO --- V1_5_4__NormalizeTableAndColumnNames: Renaming column: [ALTER TABLE authz_approvals CHANGE expiresAt expiresat timestamp  NOT NULL DEFAULT '2001-01-01 01:01:01.000001']
[2020-04-15 23:04:48.655] uaa - 23 [main] 
....  INFO --- V1_5_4__NormalizeTableAndColumnNames: Renaming column: [ALTER TABLE authz_approvals CHANGE lastModifiedAt lastmodifiedat timestamp on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;]
```

The same log fragment for MariaDB 10.2.21 (doesn't work):

```
[2020-04-16 07:15:12.376] uaa - 24 [main] ....  INFO --- V1_5_4__NormalizeTableAndColumnNames: Renaming column: [ALTER TABLE authz_approvals CHANGE expiresAt expiresat timestamp  NOT NULL DEFAULT ''2001-01-01 01:01:01.000001']
[2020-04-16 07:15:12.421] uaa - 24 [main] 
.... ERROR --- DbMigrate: Migration of schema `uaa` to version 1.5.4 - NormalizeTableAndColumnNames failed! Please restore backups and roll back database and code!
```
(Notice the unmatched `'` in the first `alter` statement)

**Comment by satadruroy** [comment] 2020-04-19 21:14
UAA issue: https://github.com/cloudfoundry/uaa/issues/1274

**Comment by fargozhu** [comment] 2020-04-24 12:14
@satadruroy I am closing it without implementation.

**Closed by fargozhu** 2020-04-24 12:14 UTC
Labels: Priority: High, Type: Bug, changelog
