### ISSUE TITLE
Deployment with Ingress Controller is not working

### ISSUE THREAD

**Issue by satadruroy** [cloudfoundry-incubator/kubecf#482] opened 2020-03-12 16:07 UTC
KubeCF 1.0

Deploy with Ingress Controller as per the instructions in https://kubecf.suse.dev/docs/getting-started/kubernetes-deploy/#ingress

UAA goes into a CLBO:

<img width="441" alt="Screen Shot 2020-03-12 at 8 59 37 AM" src="https://user-images.githubusercontent.com/6218159/76541293-93e27d80-6440-11ea-89d4-0582c702649b.png">

presumably because of:

<img width="534" alt="Screen Shot 2020-03-12 at 9 06 19 AM" src="https://user-images.githubusercontent.com/6218159/76541382-bd9ba480-6440-11ea-84a3-51ead72d90b2.png">

**Comment by satadruroy** [comment] 2020-03-12 16:11
Sort of tangential to this ticket but @troytop thinks we should bump up the default setting `nginx.ingress.kubernetes.io/proxy-body-size: 8m` to at least `64m`

**Comment by f0rmiga** [comment] 2020-03-12 16:19
Duplicate of https://github.com/cloudfoundry-incubator/kubecf/issues/475.

**Comment by f0rmiga** [comment] 2020-03-12 16:20
@satadruroy Could you open a ticket for the `proxy-body-size` default?

**Comment by f0rmiga** [comment] 2020-03-12 16:20
Closing this issue.

**Closed by f0rmiga** 2020-03-12 16:20 UTC
Labels: Priority: High
