### ISSUE TITLE
CATs failures on Eirini

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#419] opened 2020-02-27 22:04 UTC
**Describe the bug**
CATs are currently failing on Eirini:
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-eirini/builds/1

The https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-eirini/ is therefore paused for now.

**To Reproduce**
Run CATs with eirini enabled.

**Expected behavior**
Refer logs above.

**Environment**
 - CF Version: 12.18
 - Component/Plugin Name: eirini
 - Others

**Additional context**

**Comment by jimmykarily** [comment] 2020-02-28 07:03
From the logs (around where the problem starts):

```
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=routerSSL
*  start date: Feb 27 14:35:00 2020 GMT
*  expire date: Feb 26 14:35:00 2021 GMT
*  issuer: CN=routerCA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
} [5 bytes data]
> GET /read/cc-droplets/e8/a3/e8a3d174-e4e7-4337-afdd-4d961b341528/ae3d7dd1bd57203c44f1fde27701f8933564c249?md5=L5tXz28hosGMzVQdtWjjTw&expires=1582829390 HTTP/1.1

> Host: blobstore.kubecf-eirini-1582813722-3874178.172.17.0.2.nip.io

> User-Agent: curl/7.60.0

> Accept: */*

> 

{ [5 bytes data]
< HTTP/1.1 200 OK

< Accept-Ranges: bytes

< Content-Length: 21569741

< Content-Type: text/html

< Date: Thu, 27 Feb 2020 17:49:51 GMT

< Etag: "5e580124-14920cd"

< Last-Modified: Thu, 27 Feb 2020 17:49:24 GMT

< Server: nginx

< X-Vcap-Request-Id: 18ff11a2-2668-43a4-589a-d540eec03d8c

< 

{ [906 bytes data]
�X^�Zy<�kߗ�qJ�b	w��4��Q�,c��	M�ܖ��1�]D�'K�E�JE��,G%�N)e�tLY
e���r��������������~��wݟ��[��8B`ҁ�A�"�}��Q*84������~U�*V�N��8,�#�t:�_�}o�o
8�JwaM�G0�?����B��*��O��c�c���,Ru����`ҝݨ �2i_����ª����```

```

and:

```
[1mSTEP[0m: Downloading the droplet for the app
...
* Connected to api.kubecf-eirini-1582813722-3874178.172.17.0.2.nip.io (172.17.0.2) port 443 (#0)
```

it seems that some SSL communication is not setup correctly, probably the one with blobstore.

**Comment by fargozhu** [comment] 2020-03-09 17:28
@bikramnehra have you tested again after @jimmykarily comment?

**Comment by bikramnehra** [comment] 2020-03-11 23:52
> @bikramnehra have you tested again after @jimmykarily comment?

@jimmykarily is referring to the same issue that I pointed originally. _Details in pipeline logs_.

**Comment by viovanov** [comment] 2020-07-09 17:25
Duplicate of #1007

**Closed by viovanov** 2020-07-09 17:25 UTC
Labels: Status: Need More Info, suse-cap
