### ISSUE TITLE
kuecf ci needs to test upgrades from latest release to master build

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/kubecf#1039] opened 2020-06-18 22:49 UTC
Kubecf CI should test upgrades from last public release to latest master build

We need to make sure that we don't break upgrade functionality between releases.
of-course this test needs to be part of PR and forks as well, as we don't want to break our master.

**Comment by viccuad** [comment] 2020-06-19 09:17
Duplicate of https://github.com/cloudfoundry-incubator/kubecf/issues/902

**Closed by viccuad** 2020-06-19 09:17 UTC
