### ISSUE TITLE
Running kubecf:apply fails with "no deployed releases"

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/kubecf#680] opened 2020-04-14 23:34 UTC
**Describe the bug**

```
$ bazel run //dev/kubecf:apply
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //dev/kubecf:apply (32 packages loaded, 394 targets configured).
INFO: Found 1 target...
Target //dev/kubecf:apply up-to-date:
  bazel-bin/dev/kubecf/apply.rb
INFO: Elapsed time: 22.034s, Critical Path: 2.34s
INFO: 94 processes: 94 darwin-sandbox.
INFO: Build completed successfully, 117 total actions
INFO: Build completed successfully, 117 total actions
CMD ["../helm/helm", "upgrade", "kubecf", "deploy/helm/kubecf/kubecf.tgz", "--namespace", "kubecf", "--install", "--reset-values", "--values", "dev/kubecf/ingress_values.yaml", "--values", "dev/kubecf/service_values.yaml", "--values", "dev/kubecf/system_domain_values.yaml", "--values", "dev/kubecf/testing_values.yaml"]
Error: UPGRADE FAILED: "kubecf" has no deployed releases
```

**To Reproduce**

I cannot repro; just deleting the release and rerunning the command fixed it, so it may be some kind of race condition. I think I've seen it only once before. @f0rmiga asked to file a bug report anyways, in case this happens to others too.

**Environment**

Current commit: a75d7d94

**Comment by fargozhu** [comment] 2020-06-18 17:29
I am closing since it's not reproducible.

**Closed by fargozhu** 2020-06-18 17:29 UTC
Labels: Type: Bug
