### ISSUE TITLE
PR Checking with GitHub Actions

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/kubecf#1144] opened 2020-07-21 15:47 UTC
## Acceptance Criteria 

- [x] should create clusters on GKE
- [x] github actions workflow that runs smoke, CATS, SITS and brain tests for PRs
- [x] runs diego
- [x] runs eirini
- [ ] doesn't run for PRs from a fork
- [x] should cleanup any cloud resources
- [x] should not be mandatory for merges

Use the work done here as a starting point: https://github.com/mook-as/kubecf/actions/

> [x] GKE clusters should have only one node

(Edited by @mook-as: Making checkboxes)

**Comment by mook-as** [comment] 2020-09-08 16:24
@prabalsharma Should this be back to In Progress given that the mentioned PR is merged, but this task isn't complete?

**Comment by prabalsharma** [comment] 2020-09-10 16:13
I am not sure what is not working in here, but if thats the case we will have to put this back in progress or create a new card to address the shortcomings.

**Comment by viccuad** [comment] 2020-09-16 11:39
It seems that we are not running SITS, CATS as Brains are not passing (eg: https://github.com/cloudfoundry-incubator/kubecf/runs/1120154551#step:20:1609). FWIW, we are not running Brains in Concourse.

**Comment by viccuad** [comment] 2020-09-16 11:40
Also, we need to port cats-internetless and cats-eirini configuration from https://github.com/SUSE/catapult/blob/master/modules/tests/kubecf-test.sh to have feature parity with Concourse there.

**Comment by viccuad** [comment] 2020-09-29 16:56
Brains have been disabled for now.

SITS are falling, because they cannot be run for Eirini, and we are configuring Diego as Eirini (doing `FEATURE_EIRINI=false make kubecf-apply` deploys eirini, `FEATURE_EIRINI` must be empty for it to not take effect).

**Comment by mook-as** [comment] 2020-11-26 21:49
I believe at this point we have everything for the original acceptance criteria; the only missing things are:
- Don't run from forks: We're still gating runs on labels (triggered by approval).  Also, for PRs from forks, [secrets are not passed in](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow); confirmed this with a [cross-owner PR](https://github.com/mook-as/kubecf/pull/10/checks?check_run_id=1461043602) where Thulio's PR didn't have access to my secrets.  Thus I believe this is doing the correct things.
- Clean up resources: Need to clean up DNS entries; see #1630 / https://github.com/SUSE/catapult/pull/325

**Comment by mook-as** [comment] 2020-11-30 21:57
Everything here is done now; we have other outstanding tickets for other GHA things.

**Closed by mook-as** 2020-11-30 21:57 UTC
Labels: Priority: Critical, Size: 5, Type: CI
