### ISSUE TITLE
Add CATS With Eirini Enabled to KubeCF CI

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#1087] opened 2020-06-30 15:49 UTC
**Is your feature request related to a problem? Please describe.**

Currently, the KubeCF CI [pipeline](https://concourse.suse.dev/teams/main/pipelines/kubecf?group=master) does not include CATS with Eirini enabled.

**Describe the solution you'd like**

I would like to have a clone of the original pipeline where the CATS with Eirini would be included and as soon as we reach a good level of confidence we should promote to the main pipeline.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by viccuad** [comment] 2020-06-30 15:54
Needs https://github.com/SUSE/catapult/pull/241

**Comment by viccuad** [comment] 2020-06-30 16:08
Closing, duplicate of https://github.com/cloudfoundry-incubator/kubecf/issues/1007 (took me waay to much to find the correct card)

**Closed by viccuad** 2020-06-30 16:08 UTC
Labels: Priority: High, Status: Validation, Type: CI, suse-cap
