### ISSUE TITLE
CATS: Failure in internetless suite

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#144] opened 2019-11-13 10:38 UTC
**Describe the bug**

Seeing this when running CATS, with only the internetless test group enabled.

```
Summarizing 1 Failure:

[Fail] [internetless] App external traffic denied [It] denies external traffic from app containers 
/var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry/cf-acceptance-tests/internetless/app_external_traffic_denied.go:66
```

```
denies external traffic from app containers

[2019-11-06 07:40:25.37 (UTC)]> curl -k -H Expect: -s https://CATS-1-APP-9a5e25d61cfd5d90.10.104.255.255.nip.io/curl/www.google.com/80 
{"stdout":"HTTP/1.1 200 OK\r\nDate: Wed, 06 Nov 2019 07:40:26 GMT\r...
```

**To Reproduce**
N/A

**Expected behavior**
To pass

**Environment**
N/A

**Additional context**
N/A

**Comment by bikramnehra** [comment] 2019-11-22 22:53
Full running logs on latest `master`: [CATs_internetless_logs.txt](https://github.com/SUSE/kubecf/files/3881738/CATs_internetless_logs.txt)

**Comment by bikramnehra** [comment] 2019-11-25 23:02
By looking at the [docs](https://github.com/cloudfoundry/cf-acceptance-tests#explanation-of-test-groups) and [PR](https://github.com/cloudfoundry/cf-acceptance-tests/pull/346) for `internetless` CATs test suite, it seems like its expected to have a network/environment with no access to external connectivity for the application containers.

The [internetless test](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/internetless/app_external_traffic_denied.go) seems to be passing by simulating such conditions via deleting the [Default Public ASG](https://docs.cloudfoundry.org/concepts/asg.html#default-asg) which provides access to outside network:

`cf delete-security-group public_networks`

Here are the attached logs from the CATs; 
[CATs_internetless_logs_passing.txt](https://github.com/SUSE/kubecf/files/3889122/CATs_internetless_logs_passing.txt)

I have posted a [question](https://cloudfoundry.slack.com/archives/CAK2KNWC9/p1574709479004800) on CF slack#cats-users channel to confirm this. If the hypothesis is correct then either we need to drop the `internetless` test suite or have a mechanism in place to simulate such environment before running it.

**Comment by bikramnehra** [comment] 2019-11-25 23:43
@ericpromislow is helping us following up with upstream cloudfoundry to check on this issue.

**Comment by bikramnehra** [comment] 2019-11-27 23:44
@ericpromislow confirmed with upstream that the hypothesis is correct and `internetless` test suite requires specific setup/environment to be able to successfully run.

Now the question is if we do require these tests to be run as part of conformance suite for CF certification? If yes then we would need to have required setup in place.

P.S `internetless` test suite was not enabled in `SCF`.

@troytop ^

**Comment by troytop** [comment] 2019-11-28 00:55
Air-gapped CF deployments are real use cases, so we'll need these eventually. Leave this issue open till we can address this, but disable the `internetless` suite for now.

**Comment by f0rmiga** [comment] 2019-12-02 20:09
After CATS runs on CI with internet access, we should apply a network policy (https://kubernetes.io/docs/concepts/services-networking/network-policies/) to block internet access on the `diego-cell` pods and `eirini` namespace pods, then run only the `internetless` suite. The network policy should be undone after the suite runs (regardless of passing or not).

**Comment by andreas-kupries** [comment] 2020-01-15 00:12
Note: Filed #324 as an associated ticket. Currently hacking around this.

**Comment by jimmykarily** [comment] 2020-04-08 09:52
Currently the PR merging is blocked by this: https://github.com/SUSE/catapult/issues/161 (see PR comments: https://github.com/SUSE/catapult/pull/156)

**Comment by andreas-kupries** [comment] 2020-05-07 18:13
@viovanov Where do we stand wrt #161 ? @jimmykarily noted that the 161 is blocking this ticket. Has this been resolved ? and there is the new #671. It seems that these are all inter-related. Is there a specific order #144, #161 and #671 should/have to be done in ?

**Comment by viovanov** [comment] 2020-05-10 20:10
@andreas-kupries you should be able to test this locally without CI being ready yet.
Make sure your minikube/kind can't reach the internet, and run the internetless suite.

**Comment by jimmykarily** [comment] 2020-05-12 07:45
https://github.com/cloudfoundry-incubator/kubecf/issues/671
 is just tracking
https://github.com/SUSE/catapult/issues/161 on kubecf project, so they will be both closed together. #144 can be closed too when the other 2 are done. To summarize, the only thing that is not there is a way to spin up an EKCP cluster with a network plugin enabled. This is needed in order for the CI to be able to run the internetless suite.

**Comment by mudler** [comment] 2020-05-12 08:20
> #671
> is just tracking
> [SUSE/catapult#161](https://github.com/SUSE/catapult/issues/161) on kubecf project, so they will be both closed together. #144 can be closed too when the other 2 are done. To summarize, the only thing that is not there is a way to spin up an EKCP cluster with a network plugin enabled. This is needed in order for the CI to be able to run the internetless suite.

It is doable, https://github.com/SUSE/catapult/issues/161 explains how to pass to EKCP a custom kind config (which can enable/disable network plugins):

```curl -d "name=test&kindconfig=$(base64 kindconfig.yaml)" -X POST http://127.0.0.1:8030/new```

**Comment by jimmykarily** [comment] 2020-05-13 13:02
If we go the GKE way (https://github.com/cloudfoundry-incubator/kubecf/pull/859/files) we shouldn't need to do anything more. GKE clusters should have a network plugin installed already. Let's wait until the PR is closed/merged and see how we continue.

**Comment by jimmykarily** [comment] 2020-05-25 12:37
It's been a while, now catapult needs to be adapted: https://github.com/SUSE/catapult/pull/220

**Comment by jimmykarily** [comment] 2020-06-10 09:41
Merged: https://github.com/cloudfoundry-incubator/kubecf/pull/995

**Comment by jimmykarily** [comment] 2020-06-12 12:14
All good. PR merged, tests are green: https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cats-internetless-diego-master/builds/9 (needed some work in catapult to make this happen).

**Closed** 2020-06-12 12:15 UTC
Labels: Priority: Medium, SUSE, Type: Bug, Type: CI
