### ISSUE TITLE
CSR for bits should be namespaced

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/kubecf#877] opened 2020-05-15 20:26 UTC
**Describe the bug**
Bits pod going in CrashLoopBackOff

**To Reproduce**
on GKE, deploy HA kubecf with eirini enabled

**Expected behavior**
Bits goes in CLBO. However, it goes to Running state for a second after all other pods goes in running state. I think thats why this was not caught earlier by automation tests. 
As you can see below from the time stamp it goes to CLBO, running, error and then back to CLBO

```
scf           bits-79494db8cf-w8rfd                                             0/1     CrashLoopBackOff   6          8m15s
```

```
+ kubectl get pods --namespace scf
+ gawk '{ if ((match($2, /^([0-9]+)\/([0-9]+)$/, c) && c[1] != c[2] && !match($3, /Completed/)) || !match($3, /STATUS|Completed|Running/)) { print ; exit 1 } }'
bits-79494db8cf-w8rfd                            0/1     CrashLoopBackOff   7          16m
+ sleep 10
+ kubectl get pods --namespace scf
+ gawk '{ if ((match($2, /^([0-9]+)\/([0-9]+)$/, c) && c[1] != c[2] && !match($3, /Completed/)) || !match($3, /STATUS|Completed|Running/)) { print ; exit 1 } }'
+ kubectl get pods -n scf
NAME                                             READY   STATUS      RESTARTS   AGE
adapter-0                                        4/4     Running     0          12m
adapter-1                                        4/4     Running     0          12m
api-0                                            15/15   Running     1          12m
api-1                                            15/15   Running     2          5m15s
bits-79494db8cf-w8rfd                            1/1     Running     8          17m
```

```
bits-79494db8cf-w8rfd                            0/1     Error       8          17m
```

```
bits-79494db8cf-w8rfd                            0/1     CrashLoopBackOff   9          24m
```

_"error":"tls: private key does not match public key"_ :

```
Phnet4Ld/eqPlHrpE23Tq058WsERTWTWVH3I9DlQWnTuN+EWoB3lC9LgXzU\nMwGPHa69Yda5ke1lAesVw/t/b5GSxuy7b2DlCqz7tIZzQBdQh5t48iyR/fWxVdfY\nbjl4nIRzcTOF1WLhkFo0Fw==\n-----END CERTIFICATE-----\n"}
{"level":"info","ts":1589566523.8479302,"caller":"bitsgo/factory.go:334","msg":"Creating local blobstore","path-prefix":"/"}
{"level":"debug","ts":1589566523.8479633,"caller":"local/local_blobstore.go:38","msg":"GetNoRedirect","local-path":"/assets/eirinifs.tar"}
{"level":"info","ts":1589566527.9009383,"caller":"bitsgo/main.go:86","msg":"Starting with OCI image registry","registry-host":"registry.127.0.0.1.nip.io","http-enabled":true,"http-port":8888,"https-port":6666}
{"level":"info","ts":1589566527.902795,"caller":"bitsgo/main.go:200","msg":"Starting HTTPS server","ip-address":"0.0.0.0","port":6666,"public-endpoint":"registry.127.0.0.1.nip.io:6666","private-endpoint":"bits.scf.svc.cluster.local"}
{"level":"info","ts":1589566527.9030082,"caller":"bitsgo/main.go:160","msg":"Starting HTTP server","ip-address":"0.0.0.0","port":8888,"public-endpoint":"registry.127.0.0.1.nip.io:6666","private-endpoint":"bits.scf.svc.cluster.local"}
{"level":"fatal","ts":1589566527.9034812,"caller":"bitsgo/main.go:206","msg":"HTTPS server crashed","error":"tls: private key does not match public key"}
```

**Environment**

```
cf-operator     	cf-operator	1       	2020-05-15 10:57:08.408707 -0700 PDT	deployed	cf-operator-4.5.6+0.gffc6f942  	4.5.6+0.gffc6f942
susecf-scf      	scf        	1       	2020-05-15 10:57:51.415944 -0700 PDT	deployed	kubecf-2.0-RC1                 	2.0-RC1  
```

**Additional context**
_Start unsuccessful_:

```
[1589569019] CF-Logging-Smoke-Tests - 2 specs - 4 nodes S
------------------------------

[2020-05-15 18:57:21.30 (UTC)]> cf push SMOKES-3-APP-af612b666e259e44 -b binary_buildpack -m 16M -k 16M -p ../../assets/binary -d prabal-gke.ci.kubecf.charmedquarks.me 
Deprecation warning: Use of the '-d' command-line flag option is deprecated in favor of the 'routes' property in the manifest. Please see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#routes for usage information. The '-d' command-line flag option will be removed in the future.

Pushing app SMOKES-3-APP-af612b666e259e44 to org SMOKE-3-ORG-7455c8c17fab9b92 / space SMOKE-3-SPACE-2081674eb53c577c as cf_smoke_tests...
Getting app info...
Creating app with these attributes...
+ name:         SMOKES-3-APP-af612b666e259e44
  path:         /var/vcap/packages/smoke_tests/src/github.com/cloudfoundry/cf-smoke-tests/assets/binary
  buildpacks:
+   binary_buildpack
+ disk quota:   16M
+ memory:       16M
  routes:
+   smokes-3-app-af612b666e259e44.prabal-gke.ci.kubecf.charmedquarks.me

Creating app SMOKES-3-APP-af612b666e259e44...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 594 B / 594 B  100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   2020/05/15 18:57:36 Cleaning cache dir

Waiting for app to start...
FAILED
Start unsuccessful
```

**Comment by prabalsharma** [comment] 2020-05-15 20:40
I don't see smoke tests being run for eirini: https://concourse.suse.dev/teams/main/pipelines/kubecf?group=prod

**Comment by prabalsharma** [comment] 2020-05-15 20:44
non prod: May 11 2020
_Start unsuccessful_
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/smoke-tests-eirini-pr/builds/30

**Comment by gaktive** [comment] 2020-05-19 18:00
Confirm if this is the case with Eirini in non-HA. If we're clear, then we can focus on #888 for the next kubecf release and worry about Eirini HA later. bits will be deprecated soon so fixing this will be a non-priority.

**Comment by adamdunstan** [comment] 2020-05-20 12:44
I can confirm that the problem exists with Eirini in non-HA

**Comment by prabalsharma** [comment] 2020-05-20 22:56
I could not repro on SA env.
On HA, it might be due improper cleanup of bits CSR as its not namespaced

**Comment by mook-as** [comment] 2020-06-29 20:51
We can't make the CSR itself namespaced, because it's not a namespaced resource type; also, because we don't create it ourselves (the operator does).  Effectively, we can't really do anything other than clean up correctly.  But that should be fine: the operator should be deleting obsolete CSRs via https://github.com/cloudfoundry-incubator/quarks-operator/issues/952.

Closing, as there's nothing we should be doing here.

**Closed by mook-as** 2020-06-29 20:51 UTC
Labels: Priority: Medium, Type: Bug, suse-cap
