### ISSUE TITLE
CCDB encryption key rotation breaks on second rotation

### ISSUE THREAD

**Issue by satadruroy** [cloudfoundry-incubator/kubecf#524] opened 2020-03-19 17:35 UTC
Filed by @hartS 

I noticed this when I originally tested ccdb secret rotation and thought it was an intermittent issue, but after some more testing, it appears that the CCDB secret rotation breaks a kubecf deployment when performed a second time.

To repro:

After deploying kubecf, the ccdb secret can be rotated following this document, by upgrading the helm release and providing values that look like:
```ccdb:
  encryption:
    rotation:
      key_labels:
      - encryption_key_0
      - encryption_key_1
      current_key_label: encryption_key_1
```
After the kubecf deployment is ready again, the rotation can be triggered again by providing values like:
```
ccdb:
  encryption:
    rotation:
      key_labels:
      - encryption_key_0
      - encryption_key_1
      - encryption_key_2
      current_key_label: encryption_key_2
```
After attempting to rotate the secret a second time, the kubecf cluster will never recover. The status column for the api pod will show containers initializing, eventually counting up to Init:31/63 . The count will stall here for 2-3 minutes and then go into an Init:CrashLoopBackOff} or {{Init:Error state before attempting to initialize pods in the container again.

Tested with SA deployments on the latest nightly ( dd25a5e ) as well as older kubecf builds.

**Comment by HartS** [comment] 2020-03-20 12:28
"this document" refers to https://github.com/cloudfoundry-incubator/kubecf/blob/6ab22e2c290b99644f1258a01e553f8aea33f8b6/doc/secret_rotation.md

**Comment by mook-as** [comment] 2020-03-24 01:23
Since it'll be important to know _what_ was failing:

`kubectl describe pod api-0` says:
```
…
  bosh-pre-start-cloud-controller-ng:
    Container ID:  cri-o://5c5c0d63806367a66ddb8f4faa74012d0411c6c59c7675df1c63ca4cbe38705e
    Image:         docker.io/cfcontainerization/capi:SLE_15_SP1-23.8-7.0.0_374.gb8e8e6af-1.91.0
    Image ID:      docker.io/cfcontainerization/capi@sha256:8d2f66b7bec262bdb7901ff1cea2bb74cc3eccada4ab9edffc04e0e537ca1d0a
…
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
```
[Container logs] for that is attached, but nothing enlightening (just that it's around validating encryption keys, and appears to be cut off).

[Container logs]: https://github.com/cloudfoundry-incubator/kubecf/files/4372636/kube.log

**Comment by jandubois** [comment] 2020-04-09 19:43
I'm currently dealing with a related issue when importing data from an SCF export, that also breaks the cluster due to db encryption key problems. I suspect once I resolve that one, I should have a pretty good idea for this issue as well.

Not moving this to in-progress until I have finished the import story though.

**Comment by jandubois** [comment] 2020-04-16 01:09
I've been trying to repro this issue several times now, and it always works.

```
VM_DRIVER=virtualbox MINIKUBE_EXTRA_OPTIONS=--registry-mirror=http://dockerhub.home:5000 bazel run //dev/minikube:start
k create ns cf-operator
bazel run //dev/cf_operator:apply
pod-status -w
e dev/kubecf/system_domain_values.yaml
bazel run //dev/kubecf:apply
pod-status -w

SYSTEM_DOMAIN=$(kubectl get secret --namespace kubecf var-system-domain --output jsonpath='{.data.value}' | base64 --decode)
ADMIN_PASSWORD=$(kubectl get secret --namespace kubecf var-cf-admin-password --output jsonpath='{.data.password}' | base64 --decode)
cf login --skip-ssl-validation -a "https://api.${SYSTEM_DOMAIN}" -u admin -p "${ADMIN_PASSWORD}"
cf create-org suse; cf create-space -o suse myspace; cf target -o suse -s myspace
cd .../12factor
cf push
open "http://12factor.${SYSTEM_DOMAIN}"
```

Then I copied each of the rotation yaml settings above to `dev/kubecf/ccdb_values.yaml` and updated the release with `bazel run //dev/kubecf:apply`. (The first snippet above is missing the initial `ccdb:` line; I added it myself.

Each time I saw 2 dm and ig jobs after updating the release, so I re-opened https://github.com/cloudfoundry-incubator/cf-operator/issues/750 and added the corresponding information. But eventually api, cc-worker, and scheduler pods would restart and become ready again.

I tested both before and after running the rotation errand that the app was still running and accessible with

```
cf apps
open "http://12factor.${SYSTEM_DOMAIN}"
```

and things continued to work every time.

After the second rotation the user supplied values for the helm release were:

```
$ helm get values kubecf -n kubecf
USER-SUPPLIED VALUES:
ccdb:
  encryption:
    rotation:
      current_key_label: encryption_key_2
      key_labels:
      - encryption_key_0
      - encryption_key_1
      - encryption_key_2
features:
  ingress:
    enabled: false
services:
  router:
    externalIPs:
    - 192.168.99.136
    type: LoadBalancer
  ssh-proxy:
    externalIPs:
    - 192.168.99.136
    type: LoadBalancer
  tcp-router:
    externalIPs:
    - 192.168.99.136
    type: LoadBalancer
system_domain: 192.168.99.136.omg.howdoi.website
testing:
  brain_tests:
    enabled: true
  cf_acceptance_tests:
    enabled: true
  smoke_tests:
    enabled: true
```

**Comment by jandubois** [comment] 2020-04-16 17:23
After discussion with @HartS and @satadruroy we have decided to close this issue as unreproducible for now. @HartS will re-open if he finds another cluster that still shows this issue.

**Closed by jandubois** 2020-04-16 17:23 UTC
Labels: Priority: High, Status: Accepted, Type: Bug
