### ISSUE TITLE
Kubecf installation failing on Kubeadm Cluster

### ISSUE THREAD

**Issue by pramod3091** [cloudfoundry-incubator/kubecf#1124] opened 2020-07-15 12:41 UTC
**Describe the bug**
I am using 4 AWS ec2 instance and created 4 node cluster(1 master and 3 worker node) using Kubeadm.
Joined the master and worker using kubeadm join.
From master I can see that all my 4 nodes in the Ready state.

My quarks  operator deployment is successfully and pods are in running state.

With Kubecf my diego-api pod if failing and going into crashloopbackoff. Also database-Seeder pod is in notReady state.

```
ubuntu@master-node:~/eirini/kubecf$ kubectl logs diego-api-0  -n kubecf -c bbs-bbs
{"timestamp":"2020-07-13T11:41:00.770051436Z","level":"info","source":"bbs","message":"bbs.starting","data":{}}
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 1
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 2
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 3
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 4
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 5
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 6
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 7
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 8
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 9
Failed 'curl --fail --silent http://0.0.0.0:8890/ping' on attempt 10
{"timestamp":"2020-07-13T11:41:10.788663492Z","level":"fatal","source":"bbs","message":"bbs.sql-failed-to-connect","data":{"error":"Error 1045: Access denied for user 'diego'@'ip-10-244-3-64.ec2.internal' (using password: YES)","trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc000284120, 0xe8cd3f, 0x15, 0xff6860, 0xc00027b020, 0x0, 0x0, 0x0)\n\t/var/vcap/source/bbs/src/code.cloudfoundry.org/lager/logger.go:138 +0xc6\nmain.main()\n\t/var/vcap/source/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:140 +0x49f6\n"}}
panic: Error 1045: Access denied for user 'diego'@'ip-10-244-3-64.ec2.internal' (using password: YES)

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc000284120, 0xe8cd3f, 0x15, 0xff6860, 0xc00027b020, 0x0, 0x0, 0x0)
        /var/vcap/source/bbs/src/code.cloudfoundry.org/lager/logger.go:162 +0x582
main.main()
        /var/vcap/source/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:140 +0x49f6
```

```
ubuntu@master-node:~/eirini/kubecf$ kubectl logs diego-api-0  -n kubecf -c locket-locket
{"timestamp":"2020-07-13T11:41:21.580675703Z","level":"fatal","source":"locket","message":"locket.sql-failed-to-connect","data":{"error":"Error 1045: Access denied for user 'locket'@'ip-10-244-3-64.ec2.internal' (using password: YES)","trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc00012e5a0, 0xb05020, 0x15, 0xbcef20, 0xc0001d5940, 0x0, 0x0, 0x0)\n\t/var/vcap/source/locket/src/code.cloudfoundry.org/lager/logger.go:138 +0xc6\nmain.main()\n\t/var/vcap/source/locket/src/code.cloudfoundry.org/locket/cmd/locket/main.go:80 +0x1e54\n"}}
panic: Error 1045: Access denied for user 'locket'@'ip-10-244-3-64.ec2.internal' (using password: YES)
goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc00012e5a0, 0xb05020, 0x15, 0xbcef20, 0xc0001d5940, 0x0, 0x0, 0x0)
        /var/vcap/source/locket/src/code.cloudfoundry.org/lager/logger.go:162 +0x582
main.main()
        /var/vcap/source/locket/src/code.cloudfoundry.org/locket/cmd/locket/main.go:80 +0x1e54
```

```
ubuntu@master-node:~/eirini/kubecf$ kubectl get pvc -A
NAMESPACE   NAME                                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubecf      diego-cell-ephemeral-diego-cell-0               Bound    pvc-7b8d85a5-1d00-42f1-97c2-0b59796ebbf0   40Gi       RWO            local-path     48m

kubecf      pxc-data-database-0                             Bound    pvc-599cd0d0-cdd1-48de-9d48-94636530c0e9   100Gi      RWO            local-path     50m

kubecf      singleton-blobstore-pvc-singleton-blobstore-0   Bound    pvc-fecbe1da-d13c-4d23-8f93-6ca0fda730ce   100Gi      RWO            local-path     48m

```
```
ubuntu@master-node:~/eirini/kubecf$ kubectl logs database-seeder-b68825596dd4b980-qq6jm -n kubecf -c seeder
Waiting for database to be ready...
```

**To Reproduce**
Create kubeadm cluster with 1 master and 3 worker node using aws ec2 instance(t3a.xlarge * 4 of 4*16 GB) 

**Expected behavior**
Kubecf all pods should be in running state.

**Environment**
Kubecf version - v2.2.2 (I also tried with v2.3.0) getting same error
Quarks operator - v4.5.6(also tried with 5.0.0 with kubecf 2.3.0)
Kube version - v1.18.5

**Note:** I am using local path storage.

**Additional context**
Not able to get the root cause. Might be some other addon networking config is needed. Please help.
![15-kubecf](https://user-images.githubusercontent.com/27480799/87545723-0fda2400-c6c6-11ea-9073-49beac5ef189.PNG)

**Comment by jandubois** [comment] 2020-07-15 17:24
`diego-api` cannot connect to the database because the user name has not been created yet.

The user name is missing because `database-seeder` hasn't finished.

`database-seeder` didn't finish because the database is not ready yet.

There are no logs provided for the `database` pod, so I have to guess that it somehow is blocked during initialization, because it otherwise seems to be running.

I wonder if the problem is that it cannot write to the PVC provided by the Local Persistent Volume. Can you check the logs for that container please? And since the Pod is in Running state, maybe exec into the Pod and manually try to create file under the PVC mount point using the UID that the database runs under (can't remember right now if it runs as root, or a limited user).

**Comment by pramod3091** [comment] 2020-07-16 13:05
Hi @jandubois ,

Below is the database pod log for database container:

```
ubuntu@master-node:~/eirini/kubecf$ kubectl logs database-0 -n kubecf -c database                                                     
I AM database-0 - 10.244.2.215                                                                                                    
Warning: resolveip is deprecated and will be removed in a future version.                                                             
resolveip: Unable to find hostid for 'database-repl': host not found                                                                  
I am the Primary Node                                                                                                               
Removing pending files in /var/lib/mysql, because sentinel was not reached                                                            
Running --initialize-insecure on /var/lib/mysql                                                                                     
total 8.0K                                                                                                                          
drwxrwxrwx 2 root root 4.0K Jul 16 12:10 .                                                                                    
drwxr-xr-x 1 root root 4.0K Feb 25 14:45 ..                                                                                     
Finished --initialize-insecure                                                                                                       
MySQL init process in progress...                                                                                                
There were fatal errors during processing of zoneinfo directory  
                                                                                                                                                                            
MySQL init process done. Ready for start up.
```  

I tried exec into the database pod. there where 2 users available root and mysql.

```
cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
mysql:x:1001:1001:Default Application User:/home/mysql:/sbin/nologin

```



`su mysql`
 This account is currently not available.


` chsh -s /bin/bash mysql `

(setting a shell for the desired user- I did this step manually)

then logged in via mysql user. Mounted path was /root, and able to create the file on the mounted path.
```
Filesystem      Size  Used Avail Use% Mounted on
overlay          97G   14G   84G  14% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/nvme0n1p1   97G   14G   84G  14% /root
```

```
 ps -eaf | grep mysql
mysql        1     0  0 12:10 ?        00:00:01 mysqld --user=mysql --wsrep_cluster_name=kubecf-database --wsrep_node_name=database-0
--wsrep_cluster_address=gcomm:// --wsrep_sst_method=xtrabackup-v2 --wsrep_sst_auth=xtrabackup:HE9nE6ClLmQy6bQV5TvKMn5SFq3WgCFVITbOzHsQ
iTuj6k14UJvMatxOirfWHFsJ --wsrep_node_address=10.244.2.215 --pxc_strict_mode=ENFORCING
root      1394   923  0 12:18 pts/0    00:00:00 grep mysql
```

Please suggest some solution to this.

**Comment by jandubois** [comment] 2020-07-17 01:57
I wonder if this is related to k8s 1.18.x. I'm currently not set up for testing anything beyond 1.17, but hope I'll be able to take a look tomorrow.

**Comment by f0rmiga** [comment] 2020-07-17 18:30
@pramod3091 The problem is most likely with your local-path storage class. Check your storage class configuration and determine where it's trying to write in the node. Then SSH into the node and check:
1. What permissions does the destination directory of the PVCs have?
2. What filesystem does it use?

**Comment by jandubois** [comment] 2020-07-17 23:20
> I wonder if this is related to k8s 1.18.x.

I could not replicate the issue on 1.18.5.

Since the `database-seeder` still seems to be running, could you `exec` into its container and run the command that seems to indicate that the database is not ready:

```
echo "SELECT 'Ready'" | mysql --connect-timeout=3; echo $?
```

Because the seeder is just waiting in this loop:

```
       echo "Waiting for database to be ready..."
       until echo "SELECT 'Ready!'" | mysql --connect-timeout=3 1> /dev/null 2> /dev/null; do
         sleep 1
       done
```

**Comment by JimmyMa** [comment] 2020-07-23 09:07
@pramod3091  I ever had a similiar problem with local storage: I installed KubeCF twice, and the second time the database-seeder could not get ready, the root cause is that the MySQL database files were still the files in the first installation, so the db password was still the password generated in first installation. I deleted all MySQL files from the local storage, and that fixed my problem. 

Hope this helpful to you.

**Comment by jandubois** [comment] 2020-07-23 19:37
@JimmyMa That is a very good point. Just deleting the helm release is not enough; you also have to delete the PVCs:

```
$ cat scripts/kubecf-delete.sh
#!/usr/bin/env bash
source scripts/include/setup.sh

require_tools helm kubectl xargs_no_run_if_empty

helm delete kubecf --namespace "${KUBECF_NS}"
kubectl get --namespace "${KUBECF_NS}" pvc --output name | \
    xargs_no_run_if_empty kubectl delete --namespace "${KUBECF_NS}"
```

**Comment by fargozhu** [comment] 2020-10-21 12:48
I am closing 'cause it sounds that @JimmyMa issue was fixed

**Closed by fargozhu** 2020-10-21 12:48 UTC
Labels: Status: Need More Info, Type: Bug
