### ISSUE TITLE
PRs to fix patches in *cc_uploader* upstream project

### ISSUE THREAD

**Issue by fargozhu** [cloudfoundry-incubator/kubecf#520] opened 2020-03-19 15:28 UTC
[./api/cc_uploader/jobs/patch_pre-start.sh](https://github.com/cloudfoundry-incubator/kubecf/blob/master/bosh/releases/pre_render_scripts/api/cc_uploader/jobs/patch_pre-start.sh)

**Comment by fargozhu** [comment] 2020-03-19 15:28
relates with #12

**Comment by andreas-kupries** [comment] 2020-06-19 21:39
The patch removes 2 system control commands from the pre-start for cc-uploader
```
-sysctl -e -w net.ipv4.tcp_fin_timeout=10
-sysctl -e -w net.ipv4.tcp_tw_reuse=1
```

These commands are originally used to set kernel tcp configuration (ipv4 only it looks like).
Comments in the patch note:

> Remove sysctl calls as we are running in containers
cc_uploader_ctl in https://github.com/cloudfoundry/capi-release/blob/master/jobs/cc_uploader/templates/cc_uploader_ctl.erb#L26
> also skips setting those parameters.

IOW these calls are seen as useless. We either have no access to the kernel config from a container, or any such changes are ignored.

The old-style control script referenced in the comments above uses a `running_in_container` helper function. Might be useful to find its implementation, see if we can reuse that in our patch. Because in the comparison, not having this check in the prestart might be a bug in the capi-release.

**Comment by andreas-kupries** [comment] 2020-06-19 23:45
Confirmed to have no proper access. Error is
> sysctl: setting key "net.ipv4.tcp_fin_timeout": Read-only file system

**Comment by andreas-kupries** [comment] 2020-06-22 18:42
Confirmed that we can source the utils from the pre-start script, and then use the `running_in_container` to selectively disable the `sysctl` commands.

Deploys fine, and passes smoke tests. I see the new message (`Not setting ...`, see patch below) in the prestart logs.

Thus I propose to upstream the patch below:

```
--- pre-start.erb.orig	2020-06-19 16:39:07.368104919 -0700
+++ pre-start.erb	2020-06-19 16:41:32.037918289 -0700
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+source /var/vcap/all-packages/capi_utils/container_utils.sh
+
 if [ -f /var/vcap/jobs/bosh-dns/bin/is-system-resolver ]; then
   if (/var/vcap/jobs/bosh-dns/bin/is-system-resolver); then
     echo "waiting for bosh_dns"
@@ -7,5 +9,9 @@
   fi
 fi
 
-sysctl -e -w net.ipv4.tcp_fin_timeout=10
-sysctl -e -w net.ipv4.tcp_tw_reuse=1
+if running_in_container; then
+    echo "Not setting /proc/sys/net/ipv4 parameters, since I'm running inside a linux container"
+else
+    sysctl -e -w net.ipv4.tcp_fin_timeout=10
+    sysctl -e -w net.ipv4.tcp_tw_reuse=1
+fi
```

**Comment by andreas-kupries** [comment] 2020-06-22 19:11
The upstream PR is https://github.com/cloudfoundry/capi-release/pull/175

**Comment by gaktive** [comment] 2020-06-23 20:44
Since this is filed upstream now, will close. Will track the upstream PR so hopefully, when it's done, we can somehow track it to what we need to consume next.

**Comment by gaktive** [comment] 2020-09-03 17:11
Per @jandubois, the upstream patch https://github.com/cloudfoundry/capi-release/pull/175 has been merged as of last week. 

Do we have to remove our workaround as part of consuming what's now upstream?

**Comment by andreas-kupries** [comment] 2020-09-03 17:25
AFAIK our patch has to be removed now. From what @jandubois  said at the standup, he has done so ? (Don't remember anymore :(  if he mentioned a PR)

**Comment by jandubois** [comment] 2020-09-03 21:48
> Do we have to remove our workaround as part of consuming what's now upstream?

Yes, it will be removed as part of #1278, which bumps us to a version of cf-deployment that includes the patch upstream.

**Comment by gaktive** [comment] 2020-09-04 01:13
Cool, marking this as done then.

**Closed** 2020-09-04 01:14 UTC
Labels: Priority: High, Status: Follow-up, Type: Patch
