### ISSUE TITLE
suse-java-buildpack pointing to `bionic` resources

### ISSUE THREAD

**Issue by bikramnehra** [cloudfoundry-incubator/kubecf#969] opened 2020-06-01 16:42 UTC
**Describe the bug**
I am seeing following logs while pushing a java application with `sle15` stack:

```
   -----> Java Buildpack v4.30.0.1 | git@github.com:SUSE/cf-java-buildpack.git#879e7f3e
   -----> Downloading Jvmkill Agent 1.16.0_RELEASE from https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/jvmkill-1.16.0-RELEASE.so (1.0s)
   -----> Downloading Open Jdk JRE 1.8.0_242 from https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-jre-1.8.0_242-bionic.tar.gz (3.6s)
          Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.0s)
   -----> Downloading Open JDK Like Memory Calculator 3.13.0_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/bionic/x86_64/memory-calculator-3.13.0-RELEASE.tar.gz (0.6s)
          Loaded Classes: 8131, Threads: 250
   -----> Downloading Client Certificate Mapper 1.11.0_RELEASE from https://java-buildpack.cloudfoundry.org/client-certificate-mapper/client-certificate-mapper-1.11.0-RELEASE.jar (0.3s)
   -----> Downloading Container Security Provider 1.16.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-security-provider/container-security-provider-1.16.0-RELEASE.jar (0.5s)
   -----> Downloading Tomcat Instance 9.0.33 from https://java-buildpack.cloudfoundry.org/tomcat/tomcat-9.0.33.tar.gz (1.6s)
          Expanding Tomcat Instance to .java-buildpack/tomcat (0.1s)
   -----> Downloading Tomcat Access Logging Support 3.3.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-access-logging-support/tomcat-access-logging-support-3.3.0-RELEASE.jar (0.3s)
   -----> Downloading Tomcat Lifecycle Support 3.3.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-lifecycle-support/tomcat-lifecycle-support-3.3.0-RELEASE.jar (0.3s)
   -----> Downloading Tomcat Logging Support 3.3.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-logging-support/tomcat-logging-support-3.3.0-RELEASE.jar (0.3s)
   Exit status 0
   Uploading droplet, build artifacts cache...
```

**To Reproduce**
Push a java application(I used `spring-music`) with `suse-java-buildpack` and `sle15` stack.

**Expected behavior**
Ideally, while using `suse-java-buildpack` we should be using `sle` and not `bionic` resources.

**Environment**
 - CF Version
 - Component/Plugin Name
 - Others

**Additional context**
see: https://github.com/cloudfoundry/java-buildpack/blob/master/rakelib/package.rb#L36

**Comment by gaktive** [comment] 2020-07-28 20:36
Will need to move to CAP board for investigation. @satadruroy to file.

**Comment by thardeck** [comment] 2020-08-19 13:44
As far as I know having the upstream components is conscious decision and not a bug.

When converting the buildpacks to the SUSE stack we ran into the issue that many of the Java buildpack components can not be compiled by us and are taken in binary form from upstream.

To prevent legal liabilities the whole Java buildpack is taken from upstream, but still runs on our stack, just with the files from upstream. So I think this issue can be closed.

**Comment by satadruroy** [comment] 2020-08-19 15:04
Should document on the product page. @satadruroy to create an item for doc-cap.

**Comment by jandubois** [comment] 2020-08-19 16:57
This may be way out-of-date, but I thought we were using a SUSE version of openjdk, but all Java components come from upstream (they should not be platform-dependent anyways).

**Comment by thardeck** [comment] 2020-08-20 08:57
> This may be way out-of-date, but I thought we were using a SUSE version of openjdk, but all Java components come from upstream (they should not be platform-dependent anyways).

That was the original plan I think but then we decided against it.

openJDK is used for jruby in the ruby buildpack.

**Comment by jandubois** [comment] 2020-08-20 16:21
> openJDK is used for jruby in the ruby buildpack.

Yes, but it is also used in the Java buildpack to provide the JRE: https://github.com/cloudfoundry/java-buildpack/blob/03e8eec73618ca95c640fc5e834815491555f025/config/components.yml#L28-L37

As I wrote before, my info is way out of date, but I'm sure the java-buildpack uses openJDK, and the Debian/Ubuntu openJDK doesn't work on SUSE Linux; so I'm pretty sure we must be using our own.

**Comment by viovanov** [comment] 2020-09-02 07:03
@thardeck can you please update this ticket? I recall we talked about it in the planning call, but don't remember the details.

**Comment by thardeck** [comment] 2020-09-02 07:59
To my knowledge we use everything from upstream. It seems that their openJDK works on our stack.

**Comment by fargozhu** [comment] 2020-09-02 14:30
@jandubois @thardeck @viovanov do we need to extend the discussion or should we close this issue?

**Comment by jandubois** [comment] 2020-09-02 16:08
I'm fine with closing it; I'll defer to @thardeck who has more up-to-date knowledge than me.

**Closed** 2020-09-03 12:44 UTC
Labels: Priority: High, Status: Validation, Type: Bug
